### ISSUE TITLE
Error when used within a SvelteKit project

### ISSUE THREAD

**Issue by a-choyster** [aerotoad/neboa#8]
TypeError: promisify is not a function
    at node_modules/better-sqlite3/lib/methods/backup.js (backup.js:6:18)
    at __require2 (chunk-BKDDKEDW.js?v=8c4d7e6a:16:50)
    at node_modules/better-sqlite3/lib/database.js (database.js:78:29)
    at __require2 (chunk-BKDDKEDW.js?v=8c4d7e6a:16:50)
    at node_modules/better-sqlite3/lib/index.js (index.js:2:18)
    at __require2 (chunk-BKDDKEDW.js?v=8c4d7e6a:16:50)
    at neboa.ts:3:59
handleError @ app.js:20

Has anyone else come across this issue?

**Comment by aerotoad** [comment]
@a-choyster Can you post the steps to reproduce, please? I'll take a look into it

**Comment by aerotoad** [comment]
@a-choyster I just wanted to confirm where it's being used because it looks very similar to this closed issue in better-sqlite3: https://github.com/WiseLibs/better-sqlite3/issues/888

If you're putting your neboa import in something that will end up in a client bundle it won't work. The underlying better-sqlite3 and by extension neboa itself will only work in the server side.

**Comment by a-choyster** [comment]
That could be it then, ok, thanks for this, I'll mark it as closed. Thanks for your prompt reply.

**Comment by aerotoad** [comment]
I haven't worked with sveltekit or tested neboa in it, but I imagine you'll need to use neboa only inside `/lib/server`

**Comment by a-choyster** [comment]
Yeah, possibly, I'll try that now

**Comment by a-choyster** [comment]
Yup, moved the code elsewhere in the project and it works, thanks for tip @aerotoad
